### ISSUE TITLE
Index.js isn't loading React into popup.html

### ISSUE THREAD

**Issue by nick-barth** [akoskm/vite-react-tailwindcss-browser-extension-supabase#1]
Thanks for making the tutorial

Reproducible out of the box on chrome & firefox

Some change in their API perhaps?

**Comment by akoskm** [comment]
This was never part of the plugin. The popup doesn’t contain `index.js`. It's a simple HTML file

https://github.com/akoskm/vite-react-tailwindcss-browser-extension-supabase/blob/5641bd6660572b1bd10f072c81a979b28ec34d09/index.html

![Screenshot 2023-03-31 at 8 47 01 AM](https://user-images.githubusercontent.com/3111627/229044259-fa2b1cd5-e454-40ca-9453-58042dd8411b.jpg)

**Comment by ytsheng** [comment]
@akoskm, can you show steps to display the login page from the supabase? What is being shown in this [blog](https://akoskm.com/how-to-connect-browser-extensions-to-supabase) and what is available from the github repo is inconsistent. The blog shows the login UI to supabase, however this repo only displays the index.html UI. Curious if you can allude to what will make the login UI show up?
