### ISSUE TITLE
Auth not persisting when popup closed and opened

### ISSUE THREAD

**Issue by jakecollins1** [akoskm/vite-react-tailwindcss-browser-extension-supabase#2]
Hello @akoskm! 

I am following along your blog post tutorial for something I am working on, with one tweak where I moved the react app with the auth forms to live in the popup.  I have the flow working, with a session returning, but after closing and opening the popup, `getSession` returns null.  I don't know where supabase stores the cookie auth token in this example, I couldn't find them in the dev tools of the page or the popup.  Is there a way to manually set a cookie for the extension only, that would persist across domains?  Or is there a set of best practices I am not following when you want to auth into an extension across domains?

ps - I know this isn't an issue with this repo, so feel free to close

thanks for your time, and for the great blog post!

**Comment by akoskm** [comment]
Hi Jake!

> Is there a way to manually set a cookie for the extension only that would persist across domains?

I recently built a plugin that needed cross-site auth information stored, and I used `chrome.storage` to achieve that.

You could combine `chrome.storage` with supabase [`createClient`](https://supabase.com/docs/reference/javascript/initializing) function, which accepts an `options.auth.storage` where you can provide your own storage implementation.

I haven't tested this but  here's how I would do it with `chrome.storage`:

```
function getCustomStorage() {
  return {
    async getItem(key) {
      const storageResult = await chrome.storage.sync.get([key]);
      return storageResult[key];
    },
    async setItem(key, value) {
      await chrome.storage.sync.set({ [key]: value });
    },
    async removeItem ...
  }
}

export const supabase = createClient(supabaseUrl!, supabaseAnonKey!, {
  options.auth = {
    storage: getCustomStorage()
  };
})
```

**Comment by jakecollins1** [comment]
Akos - 
That was exactly what I needed.  Thanks and have a great day!
Jake
