### ISSUE TITLE
Index.html  VS App.ts

### ISSUE THREAD

**Issue by ytsheng** [akoskm/vite-react-tailwindcss-browser-extension-supabase#3]
@akoskm, can you show steps to display the login page from the supabase? What is being shown in this [blog](https://akoskm.com/how-to-connect-browser-extensions-to-supabase) and what is available from the github repo is inconsistent. The blog shows the login UI to supabase, however this repo only displays the index.html UI. Curious if you can allude to what will make the login UI show up?

**Comment by ytsheng** [comment]
Fixed it on chrome: https://github.com/akoskm/vite-react-tailwindcss-browser-extension-supabase/pull/4

**Comment by akoskm** [comment]
The login page should show up when you visit https://blank.org. The extension manifest file enables the plugin only on that domain: https://github.com/akoskm/vite-react-tailwindcss-browser-extension-supabase/blob/fe773081ed0fe07aa9d9f27c08c33f5be60eadc5/public/manifest.json#L15-L17

**Comment by ytsheng** [comment]
Do you have sample code that shows you inserting into supabase, that code should exist in the background.jsx right rather than in the contentscript?

**Comment by akoskm** [comment]
This extension is not doing any inserts. But you're correct, that should be done in the background script.

See the [Insert data](https://supabase.com/docs/reference/javascript/insert) section of the documentation.
